# Generated by Django 3.1 on 2023-06-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gstin',
            field=models.CharField(max_length=15, null=True, verbose_name='gstin'),
        ),
    ]
