# Generated by Django 3.1 on 2023-06-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20230619_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='tax_preference',
            field=models.CharField(choices=[(1, 'Taxable'), (2, 'Non Taxable')], default=1, max_length=100),
        ),
    ]
