# Generated by Django 3.1 on 2023-06-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20230623_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tax',
        ),
        migrations.AddField(
            model_name='transaction',
            name='central_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='state_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='taxable_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
