# Generated by Django 3.1 on 2023-06-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20230623_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_taxable_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
