# Generated by Django 3.1 on 2023-06-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20230624_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
