# Generated by Django 3.1 on 2023-06-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20230620_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tax_rate_state',
            new_name='state_tax_rate',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='media/item_images'),
        ),
    ]
