# Generated by Django 3.1 on 2023-06-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_inventoryadjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustments',
            name='ADJUSTMENT_TYPE',
            field=models.IntegerField(choices=[(1, 'Increase'), (2, 'Decrease')], default=2),
        ),
    ]
