# Generated by Django 3.1 on 2023-06-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_inventoryadjustments_adjustment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.itemgroup'),
        ),
    ]
