# Generated by Django 3.1 on 2023-06-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20230624_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salereturn',
            name='status',
        ),
    ]
