# Generated by Django 3.1 on 2023-06-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_salereturn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Redeemed')], default=1),
        ),
    ]
