# Generated by Django 3.1 on 2023-06-25 04:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_salereturn_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('company', models.CharField(max_length=50, verbose_name='company')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('address', models.TextField()),
                ('website', models.CharField(max_length=50, verbose_name='website')),
                ('gstin', models.CharField(max_length=15, null=True, verbose_name='gstin')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
