# Generated by Django 3.1 on 2023-06-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, verbose_name='invoice_no')),
                ('file_invoice', models.FileField(upload_to='media/invoice_files', verbose_name='invoice_file')),
                ('date', models.DateField(verbose_name='date')),
                ('total_taxable_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.CharField(max_length=50, null=True, verbose_name='website'),
        ),
        migrations.CreateModel(
            name='PurchaseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('state_tax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('central_tax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.purchaseinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.item')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.vendor'),
        ),
    ]
