# Generated by Django 3.1 on 2023-06-21 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_auto_20230621_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.customer'),
        ),
    ]
