# Generated by Django 3.1 on 2023-06-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20230625_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='valid'),
        ),
    ]
