# Generated by Django 3.2.19 on 2023-06-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_auto_20230627_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcreditnote',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Redeemed')], default=1),
        ),
    ]
