# Generated by Django 3.2.19 on 2023-07-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_vendorcreditnote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pancard',
            field=models.CharField(max_length=15, null=True, verbose_name='pancard'),
        ),
    ]
