# Generated by Django 3.2.19 on 2023-07-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_auto_20230719_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='save_last_rate',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=2),
        ),
    ]
