# Generated by Django 3.2.19 on 2023-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_customer_save_last_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='phone'),
        ),
    ]
