# Generated by Django 4.2.3 on 2023-07-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_alter_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='central_tax_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='integrated_tax_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='integrated_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='state_tax_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='central_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
