# Generated by Django 4.2.3 on 2023-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_item_central_tax_rate_item_integrated_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='extra_details',
            field=models.JSONField(null=True),
        ),
    ]
