# Generated by Django 4.2.3 on 2023-08-12 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_invoice_extra_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('state', models.IntegerField(choices=[(1, 'Andaman & Nicobar Islands'), (2, 'Andhra Pradesh'), (3, 'Arunachal Pradesh'), (4, 'Assam'), (5, 'Bihar'), (6, 'Chandigarh'), (7, 'Chhattisgarh'), (8, 'Dadra & Nagar Haveli and Daman & Diu'), (9, 'Delhi'), (10, 'Goa'), (11, 'Gujarat'), (12, 'Haryana'), (13, 'Himachal Pradesh'), (14, 'Jammu & Kashmir'), (15, 'Jharkhand'), (16, 'Karnataka'), (17, 'Kerala'), (18, 'Ladakh'), (19, 'Lakshadweep'), (20, 'Madhya Pradesh'), (21, 'Maharashtra'), (22, 'Manipur'), (23, 'Meghalaya'), (24, 'Mizoram'), (25, 'Nagaland'), (26, 'Odisha'), (27, 'Puducherry'), (28, 'Punjab'), (29, 'Rajasthan'), (30, 'Sikkim'), (31, 'Tamil Nadu'), (32, 'Telangana'), (33, 'Tripura'), (34, 'Uttarakhand'), (35, 'Uttar Pradesh'), (36, 'West Bengal')], default=1)),
            ],
            options={
                'verbose_name': 'ShippingDetail',
                'verbose_name_plural': 'ShippingDetails',
            },
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.shippingdetail'),
        ),
    ]
