# Generated by Django 4.2.3 on 2024-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_relatedfile_remove_purchaseinvoice_changed_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoicedetails',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseinvoicedetails',
            name='total_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoicedetails',
            name='total_taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
