# Generated by Django 4.2.3 on 2024-05-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0033_alter_purchaseinvoicedetails_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.purchaseinvoicedetails'),
        ),
    ]
