# Generated by Django 4.2.3 on 2024-05-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0037_alter_invoice_extra_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='extra_details',
            field=models.JSONField(default=dict),
        ),
    ]
